### ISSUE TITLE
What is the size basis for our game?

### ISSUE THREAD

**Issue by Regulator13** [Phabbits/Adrift#11]
32X32? 16X16?

**Comment by afrey15** [comment]
I need 32X32 for the art style I am hoping for. I've got units at around 24X24 moving freely within that grid

**Comment by Regulator13** [comment]
Okay, this is actually for a Macaga test game Gabe and I are making to get used to GitHub, glad you're getting into it though!

**Comment by afrey15** [comment]
Nice. Loving the communication system on here lol
